version: '3.5'
services:
  load:
    build: .
    ports:
      - 80:80
      - 4000:3000
    volumes:
      - ./:/var/www/html
    env_file: .env
    links:
      - mysql
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}

  mysql:
    image: mysql:5.7.13
    container_name: load-mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=cmms
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

volumes:
  mysql:
    driver: local
